import type { Metadata } from 'next';
import { Fredoka } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import './globals.css';
import Navbar, { BottomNavBar } from './components/Navbar';
import Footer from './components/Footer';
import { Toaster } from './components/ui/sonner';
import { Suspense } from 'react';
import Overlay from './components/Overlay';
import { SearchOverlay } from './components/Search';
import SearchContextProvider from './context/SearchContext';

const fredoka = Fredoka({
  variable: '--font-Fredoka',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.className} antialiased`}>
        <Suspense>
          <NextTopLoader showSpinner={false} />
        </Suspense>
        <SearchContextProvider>
          <Navbar />
          <SearchOverlay />
          <BottomNavBar />
        </SearchContextProvider>

        <main>{children}</main>
        <Toaster
          toastOptions={{ className: fredoka.className }}
          className={`${fredoka.className}  antialiased`}
        />
        <Footer />
        {/* <SearchContextProvider></SearchContextProvider> */}
      </body>
    </html>
  );
}
